const page = document.body.dataset.page;
const seed = {products:[{id:'INV-001',name:'Wireless keyboard',category:'Electronics',qty:48,min:10,price:1290},{id:'INV-002',name:'USB-C hub',category:'Electronics',qty:8,min:12,price:1890},{id:'INV-003',name:'Desk organizer',category:'Office',qty:64,min:15,price:450},{id:'INV-004',name:'Notebook set',category:'Office',qty:120,min:25,price:280},{id:'INV-005',name:'LED desk lamp',category:'Furniture',qty:0,min:8,price:1650},{id:'INV-006',name:'Ergonomic chair',category:'Furniture',qty:18,min:5,price:6500}],movements:[]};
let data;
try { data=JSON.parse(localStorage.getItem('stockroom-v1')) || structuredClone(seed); if(!Array.isArray(data.products)||!Array.isArray(data.movements)) throw Error(); } catch { data=structuredClone(seed); }
const money = n => new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(n);
const escape = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status = p => p.qty===0?'Out of stock':p.qty<=p.min?'Low stock':'In stock';
let toastTimer;
function toast(message){const el=document.querySelector('.toast');el.textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.textContent='',4000);}
function save(){try{localStorage.setItem('stockroom-v1',JSON.stringify(data));return true;}catch{toast('Browser storage is unavailable. Changes are kept for this page only.');return false;}}
const titles={dashboard:['Overview','Your inventory, at a glance.'],products:['Products','Manage your catalog and keep every item in view.'],movements:['Stock movements','Track what comes in and what goes out.'],reports:['Reports','A clear view of your stock and inventory value.']};
const links=[['dashboard','index.html','Overview'],['products','products.html','Products'],['movements','movements.html','Stock movements'],['reports','reports.html','Reports']];
document.querySelector('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="index.html">stock<span>room.</span></a><div class="nav-label">WORKSPACE</div><nav>${links.map(([key,url,label])=>`<a href="${url}" class="${page===key?'active':''}" ${page===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><footer>Sample workspace<br>Local inventory · PHP</footer></aside><main class="workspace"><div class="topbar"><span>Workspace / ${titles[page][0]}</span><div class="avatar" aria-label="Sample workspace">SR</div></div><div class="heading"><div><div class="eyebrow">INVENTORY MANAGEMENT</div><h1>${titles[page][0]}</h1><p>${titles[page][1]}</p></div><button id="primary">${page==='products'?'+ Add product':page==='movements'?'+ Record movement':'Export inventory'}</button></div><div id="content"></div><p class="footnote">Demo inventory · Changes are saved in this browser. Export a CSV to keep a copy.</p></main><dialog id="editor"></dialog><div class="toast" role="status" aria-live="polite"></div>`;
function stats(){const units=data.products.reduce((s,p)=>s+p.qty,0),value=data.products.reduce((s,p)=>s+p.qty*p.price,0),low=data.products.filter(p=>p.qty<=p.min).length;return `<div class="stats">${[['Total products',data.products.length,'Across your catalog'],['Units in stock',units,'Available inventory'],['Inventory value',money(value),'Based on unit cost'],['Needs attention',low,'At or below reorder level']].map(([label,value,hint])=>`<div class="card stat"><div class="label">${label}</div><strong>${value}</strong><div class="hint">${hint}</div></div>`).join('')}</div>`;}
function productRows(products){return products.map(p=>`<tr><td><b>${escape(p.name)}</b><small>${escape(p.id)}</small></td><td>${escape(p.category)}</td><td>${p.qty}</td><td>${money(p.price)}</td><td><span class="badge ${p.qty===0?'out':p.qty<=p.min?'low':''}">${status(p)}</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No products match your filters.</td></tr>';}
function table(products){return `<div class="table-wrap"><table><thead><tr><th>PRODUCT / SKU</th><th>CATEGORY</th><th>QUANTITY</th><th>UNIT COST</th><th>STATUS</th></tr></thead><tbody id="product-rows">${productRows(products)}</tbody></table></div>`;}
function categories(){const cats=[...new Set(data.products.map(p=>p.category))];return cats.map(c=>({name:c,units:data.products.filter(p=>p.category===c).reduce((s,p)=>s+p.qty,0)}));}
function charts(){const cats=categories(),max=Math.max(1,...cats.map(c=>c.units)),total=Math.max(1,cats.reduce((s,c)=>s+c.units,0));return `<div class="grid"><section class="card"><div class="panel-heading"><div><h2>Stock by category</h2><p>Available units across your catalog</p></div></div><div class="chart">${cats.map(c=>`<div class="bar-group"><span>${c.units}</span><div class="bar" style="height:${Math.max(1,c.units/max*160)}px" aria-label="${escape(c.name)}: ${c.units} units"></div><span>${escape(c.name)}</span></div>`).join('')}</div><div class="legend">Current inventory · Live totals</div></section><section class="card"><h2>Inventory mix</h2><p>Share of available units</p>${cats.map(c=>`<div class="category"><div class="row"><span>${escape(c.name)}</span><b>${Math.round(c.units/total*100)}%</b></div><div class="track"><div class="fill" style="width:${c.units/total*100}%"></div></div></div>`).join('')}</section></div>`;}
function render(){const target=document.querySelector('#content');if(page==='dashboard'||page==='reports'){const low=data.products.filter(p=>p.qty<=p.min);target.innerHTML=stats()+(low.length?`<div class="notice">${low.length} products need attention. <a href="products.html">Review your inventory →</a></div>`:'')+charts()+`<section class="card"><div class="panel-heading"><div><h2>${page==='reports'?'Reorder report':'Product overview'}</h2><p>${page==='reports'?'Items at or below their reorder level':'A snapshot of your current stock'}</p></div><a href="products.html">View all products →</a></div>${table(page==='reports'?low:data.products.slice(0,6))}</section>`;}
if(page==='products'){target.innerHTML=stats()+`<section class="card"><div class="toolbar"><input id="search" type="search" placeholder="Search products or SKU…" aria-label="Search products"><select id="category" aria-label="Filter category"><option value="">All categories</option>${categories().map(c=>`<option>${escape(c.name)}</option>`).join('')}</select><select id="status" aria-label="Filter status"><option value="">All statuses</option><option>In stock</option><option>Low stock</option><option>Out of stock</option></select></div>${table(data.products)}</section>`;const filter=()=>{const term=document.querySelector('#search').value.toLowerCase(),cat=document.querySelector('#category').value,state=document.querySelector('#status').value;document.querySelector('#product-rows').innerHTML=productRows(data.products.filter(p=>(p.name+' '+p.id).toLowerCase().includes(term)&&(!cat||p.category===cat)&&(!state||status(p)===state)));};['search','category','status'].forEach(id=>document.getElementById(id).addEventListener('input',filter));}
if(page==='movements'){target.innerHTML=stats()+`<section class="card"><div class="panel-heading"><div><h2>Movement history</h2><p>Every recorded adjustment, in one place</p></div></div><div class="table-wrap"><table><thead><tr><th>PRODUCT</th><th>TYPE</th><th>UNITS</th><th>DATE</th><th>NOTE</th></tr></thead><tbody>${data.movements.slice().reverse().map(m=>`<tr><td>${escape(m.name)}</td><td><span class="badge ${m.type==='out'?'low':''}">${m.type==='in'?'Stock in':'Stock out'}</span></td><td>${m.type==='in'?'+':'−'}${m.qty}</td><td>${escape(new Date(m.date).toLocaleString())}</td><td>${escape(m.note||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No movements yet. Record your first stock adjustment above.</td></tr>'}</tbody></table></div></section>`;}}
function openEditor(){const dialog=document.querySelector('#editor');const productMode=page==='products';dialog.innerHTML=`<form id="edit-form"><h2>${productMode?'Add product':'Record movement'}</h2>${productMode?'<label>Product name<input name="name" required maxlength="80"></label><label>Category<select name="category"><option>Electronics</option><option>Office</option><option>Furniture</option><option>Other</option></select></label><label>Unit cost (PHP)<input name="price" type="number" min="0" max="100000000" step="0.01" required></label><label>Reorder level<input name="min" type="number" min="0" max="1000000" step="1" value="10" required></label>':`<label>Product<select name="id" required>${data.products.map(p=>`<option value="${escape(p.id)}">${escape(p.name)} (${p.qty} available)</option>`).join('')}</select></label><label>Movement type<select name="type"><option value="in">Stock in</option><option value="out">Stock out</option></select></label>`}<label>${productMode?'Starting quantity':'Quantity'}<input name="qty" type="number" min="${productMode?0:1}" max="1000000" step="1" required></label>${productMode?'':'<label>Note<input name="note" maxlength="150" placeholder="Delivery, sale, adjustment…"></label>'}<div class="actions"><button type="button" class="secondary" id="cancel">Cancel</button><button type="submit">Save ${productMode?'product':'movement'}</button></div></form>`;dialog.querySelector('#cancel').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const fields=new FormData(e.target),qty=Number(fields.get('qty'));if(!Number.isSafeInteger(qty)||qty<0){toast('Enter a valid whole-number quantity.');return;}if(productMode){const name=fields.get('name').trim();if(!name){toast('Enter a product name.');return;}let next=1;while(data.products.some(p=>p.id==='INV-'+String(next).padStart(3,'0')))next++;data.products.push({id:'INV-'+String(next).padStart(3,'0'),name,category:fields.get('category'),price:Number(fields.get('price')),min:Number(fields.get('min')),qty});}else{const p=data.products.find(p=>p.id===fields.get('id'));if(!p||qty<1){toast('Select a product and valid quantity.');return;}const type=fields.get('type');if(type==='out'&&qty>p.qty){toast('Not enough stock for this movement.');return;}p.qty+=type==='in'?qty:-qty;data.movements.push({name:p.name,type,qty,date:new Date().toISOString(),note:fields.get('note').trim()});}const persisted=save();dialog.close();render();if(persisted)toast(productMode?'Product added successfully.':'Stock updated successfully.');};dialog.showModal();}
function exportCSV(){const rows=[['SKU','Product','Category','Quantity','Unit cost','Reorder level'],...data.products.map(p=>[p.id,p.name,p.category,p.qty,p.price,p.min])];const csv=rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download='stockroom-inventory.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Inventory exported.');}
document.querySelector('#primary').onclick=page==='products'||page==='movements'?openEditor:exportCSV;
window.addEventListener('storage',e=>{if(e.key==='stockroom-v1'){try{const fresh=JSON.parse(e.newValue);if(fresh&&Array.isArray(fresh.products)&&Array.isArray(fresh.movements)){data=fresh;render();}}catch{}}});
render();